const playerData = [
  {
    profile: {
      firstName: 'Thibaut',
      lastName: 'Courtois',
      nationalTeam: 'Belgium',
      position: 'Goalkeeper',
      price: 7000000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'Jordan',
      lastName: 'Pickford',
      nationalTeam: 'England',
      position: 'Goalkeeper',
      price: 7000000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'Hugo',
      lastName: 'Lloris',
      nationalTeam: 'France',
      position: 'Goalkeeper',
      price: 7000000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'Koen',
      lastName: 'Casteels',
      nationalTeam: 'Belgium',
      position: 'Goalkeeper',
      price: 6500000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'Kevin',
      lastName: 'Walker',
      nationalTeam: 'England',
      position: 'Defender',
      price: 7000000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'Harry',
      lastName: 'Maguire',
      nationalTeam: 'England',
      position: 'Defender',
      price: 6500000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'Kaan',
      lastName: 'Ayhan',
      nationalTeam: 'Turkey',
      position: 'Defender',
      price: 4000000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'Yukhym',
      lastName: 'Konoplya',
      nationalTeam: 'Ukraine',
      position: 'Midfielder',
      price: 5500000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'Koko',
      lastName: 'Mrdin',
      nationalTeam: 'Switzerland',
      position: 'Midfielder',
      price: 4000000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'Ela',
      lastName: 'Eker',
      nationalTeam: 'Poland',
      position: 'Forward',
      price: 9000000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'Cuma',
      lastName: 'Beykoz',
      nationalTeam: 'Austria',
      position: 'Midfielder',
      price: 5000000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'Mkenzie',
      lastName: 'Hontus',
      nationalTeam: 'Italy',
      position: 'Midfielder',
      price: 7800000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'Ryan',
      lastName: 'Maehle',
      nationalTeam: 'Denmark',
      position: 'Midfielder',
      price: 4500000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
];

const addPlayers = () => {
  playerData.map(async (player) => {
    try {
      await firestore().collection('players').add(player);
    } catch (error) {
      console.log();
    }
  });
};
