const playerData = [
  {
    profile: {
      firstName: 'Harry',
      lastName: 'Kane',
      nationalTeam: 'England',
      position: 'Forward',
      price: 13500000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'Kylian',
      lastName: 'Mbappé',
      nationalTeam: 'France',
      position: 'Forward',
      price: 7000000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'Romelo',
      lastName: 'Lukaku',
      nationalTeam: 'Belgium',
      position: 'Forward',
      price: 11500000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'Marcus',
      lastName: 'Rashford',
      nationalTeam: 'England',
      position: 'Forward',
      price: 6500000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'Antoine',
      lastName: 'Griezmann',
      nationalTeam: 'France',
      position: 'Forward',
      price: 10500000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'Cristiano',
      lastName: 'Ronaldo',
      nationalTeam: 'Portugal',
      position: 'Forward',
      price: 10000000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'Álvaro',
      lastName: 'Morata',
      nationalTeam: 'Spain',
      position: 'Forward',
      price: 10000000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'Robert',
      lastName: 'Lewandowski',
      nationalTeam: 'Poland',
      position: 'Forward',
      price: 9000000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'Andrea',
      lastName: 'Belotti',
      nationalTeam: 'Italy',
      position: 'Forward',
      price: 8500000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'João',
      lastName: 'Félix',
      nationalTeam: 'Portugal',
      position: 'Forward',
      price: 8500000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'Ivan',
      lastName: 'Perišić',
      nationalTeam: 'Croatia',
      position: 'Forward',
      price: 8000000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'Luuk',
      lastName: 'de Jong',
      nationalTeam: 'Netherlands',
      position: 'Forward',
      price: 8000000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
  {
    profile: {
      firstName: 'Martin',
      lastName: 'Braithwaite',
      nationalTeam: 'Denmark',
      position: 'Forward',
      price: 7500000,
    },
    stats: {
      points: 0,
      goals: 0,
      hattricks: 0,
      assists: 0,
      minutes: 0,
      yellowCards: 0,
      redCards: 0,
      ownGoals: 0,
      goalsConceded: 0,
      penaltiesSaved: 0,
      cleanSheets: 0,
      penaltiesMissed: 0,
    },
  },
];

const addPlayers = () => {
  playerData.map(async (player) => {
    try {
      await firestore().collection('players').add(player);
    } catch (error) {
      console.log(error);
    }
  });
};
